apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dns
  namespace: kube-system
data:
  stubDomains: |
    {"somedomain.dom": ["192.168.1.2", "192.168.1.3"]}
  upstreamNameservers: |
    ["192.168.1.2", "8.8.8.8", "8.8.4.4"]